### ISSUE TITLE
`zerocopy` 0.6.2 is not semver compatible with `0.6.1`: use zerocopy::U32;    |     ^^^^^^^^^^^^^ no `U32` in the root

### ISSUE THREAD

**Issue by alamb** [google/zerocopy#228]
Hi, thank you for this crate. 

# Problem 

When `zerocopy` `0.6.2` was released to crates.io our CI tests started failing like this:

```
error[E0432]: unresolved import `zerocopy::U32`
  --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/apache-avro-0.15.0/src/duration.rs:19:5
   |
19 | use zerocopy::U32;
   |     ^^^^^^^^^^^^^ no `U32` in the root
   |
help: consider importing one of these items instead
   |
19 | use digest::consts::U32;
   |     ~~~~~~~~~~~~~~~~~~~
19 | use rand::seq::index::IndexVec::U32;
   |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19 | use rand::seq::index::IndexVecIntoIter::U32;
   |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19 | use rand::seq::index::IndexVecIter::U32;
   |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     and 1 other candidate
```

We can fix our build by pinning to `zerocopy 0.6.1`

Here is the downstream ticket: https://github.com/apache/arrow-datafusion/issues/7221

Note that DataFusion uses `zerocopy` transitively the avro crate so I can't change the use of `zerocopy` directly

# Requested solution

If you agree that `0.6.2` is not semver compatible with 0.6.1, can you please [yank](https://doc.rust-lang.org/cargo/commands/cargo-yank.html) the `0.6.2` crate from crates.io

**Comment by alamb** [comment]
It looks like the aliases were changed in https://github.com/google/zerocopy/pull/101

**Comment by alamb** [comment]
cc @joshlf  as you see to be the owner on crates.io

**Comment by joshlf** [comment]
I've yanked 0.6.2, and I'll work on a fix that I'll publish as 0.6.3.

**Comment by alamb** [comment]
Thank you for your quick response @joshlf

**Comment by joshlf** [comment]
Hey @alamb, it actually looks like the issue was caused by us introducing a new default feature (`byteorder`) and putting some existing functionality behind that feature (the `pub use crate::byteorder::*;` in the crate root). It looks like apache-avro version 0.15.0 depends on zerocopy with `default-features = false`.

I'm not sure yet how I'm going to fix this in order to release 0.6.3. One option is just to remove the `byteorder` feature and wait until the next major version to release it, but I'm not yet convinced that that's definitely the right move. I'll keep you updated to make sure that 0.6.3 doesn't cause any more breakage.

**Comment by joshlf** [comment]
Hey @alamb, I've published 0.6.3-alpha. Would you be able to test to see if it causes breakage on your side before I publish it as 0.6.3?

**Comment by alamb** [comment]
@joshlf  I will do so ...

**Comment by alamb** [comment]
Update: `0.6.3-alpha` (from the https://github.com/google/zerocopy/tree/v0.6.x branch) seems to compile well for our project. 

I am running it through our full CI here: https://github.com/apache/arrow-datafusion/pull/7227

**Comment by joshlf** [comment]
Thanks for doing that, @alamb! I'll release 0.6.3 soon (once https://github.com/google/zerocopy/pull/232 merges).

**Comment by joshlf** [comment]
Okay, [it's been published](https://crates.io/crates/zerocopy/0.6.3)!

**Comment by alamb** [comment]
FWIW our latest CI run picked up `0.6.3` and seems to have passed successfully: https://github.com/apache/arrow-datafusion/actions/runs/5797783905/job/15714083065

Thanks again @joshlf

**Comment by joshlf** [comment]
Awesome! You're very welcome!
